name: Instructional Architecture
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4005
title: Instructional Architecture
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77147790-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#556a85'
    - '#638cc0'
    - '#263646'
    - '#b1c1ce'
  brandStrength: 0.5
  lightness: 0.7942776465788484
  saturation: 0.765507438685745
  rhythmicContrast: 0.23634098190814257
purpose: []
